In [2]:
for i in range(11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [3]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9


In [5]:
i=0
while(i<10):
    i=i+2
    print(i)

2
4
6
8
10


In [6]:
num=int(input("Enter a number="))
if(num%2==0):
    print("Number is even")
else:
    print("Number is odd")

Enter a number= 4


Number is even


In [8]:
x=input("enter string=")
y=x[::-1]
print(y)

enter string= messi


issem


In [11]:
x=input("enter a string")
y=x[::-1]
if(y==x):
    print("palindrome")
else:
    print("not a palindrome")

enter a string malayalam


palindrome


In [25]:
x=input("enter a string") #hello
y=''
for i in x:
    y=i+y
print(y)
if(x==y):
    print("palindrome")
else:
    print("not palindrome")
    

enter a string kkj


jkk
not palindrome


In [33]:
a=5%2
print(a)

1


In [34]:
a=5
a+=2
print(a)

7


In [36]:
print(5==2)

False


In [37]:
True or True

True

In [38]:
True or False

True

In [39]:
False or False

False

In [40]:
True and True

True

In [41]:
True and False

False

In [42]:
not True

False

In [43]:
not False

True

In [49]:
if (5>2):
    print('ge')
elif (2>3):
    print('jj')
else:
    print('ff')

ge


In [55]:
a=[1, 2, 3, 4, 5, 6, 7, 8, 9]
for i in "helloJ":
    print(i)

h
e
l
l
o
J


In [6]:
x=0
while x<10:
    while True:
        if x>3:
            break
        print(x)
        
        x+=1
    print(x)
    x+=1
print("now exited")

0
1
2
3
4
5
6
7
8
9
now exited


In [14]:
a=0
while True:
    a+=1
    if a==4:
        continue     
    if a > 5:
        break
    print(a)
    

1
2
3
5


In [15]:
yr=int(input("Enter a year="))
if yr%100==0 and yr%400==0:
    print("Leap year")
elif yr%4==0:
    print("leap year")
else:
    print("not a year")
    

Enter a year= 2028


leap year


In [25]:
yr=int(input("Enter a year="))

if yr%4==0:
    if yr%100==0:
        if yr%400==0:
            print("Leap year")
        else:
            print("not a leapyear")
    else:
        print('leap year')
else:
    print("not a leap year")
    

Enter a year= 2028


leap year


In [20]:
n=int(input("Enter a number="))
s=0
for i in range(1,n):
    s=s+i
print("sum-",s)

Enter a number= 5


sum- 10


In [21]:
n=int(input("enter a number"))
for i in range(1,11):
    print(i,"X",n,"=",i*n)

enter a number 5


1 X 5 = 5
2 X 5 = 10
3 X 5 = 15
4 X 5 = 20
5 X 5 = 25
6 X 5 = 30
7 X 5 = 35
8 X 5 = 40
9 X 5 = 45
10 X 5 = 50


In [3]:
xlist=["abc",123,456,"xyz",[1,3,4]]
print(xlist)

['abc', 123, 456, 'xyz', [1, 3, 4]]


In [4]:
type(xlist)

list

In [5]:
xtup=("abc",123,456,"xyz",[1,3,4])
print(xtup)
type(xtup)

('abc', 123, 456, 'xyz', [1, 3, 4])


tuple

In [6]:
xlist=["abc",123,456,"xyz",[1,3,4]]
xlist.append(333)
print(xlist)

['abc', 123, 456, 'xyz', [1, 3, 4], 333]


In [8]:
xlist=["abc",123,456,"xyz",[1,3,4]]
xlist.insert(0,"fcb")
print(xlist)

['fcb', 'abc', 123, 456, 'xyz', [1, 3, 4]]


In [10]:
xlist=["abc",123,456,"xyz",[1,3,4]]
xl2=["sad","happy","angry"]
xlist.extend(xl2)
print(xlist)

['abc', 123, 456, 'xyz', [1, 3, 4], 'sad', 'happy', 'angry']


In [11]:
xlist=["abc",123,456,"xyz",[1,3,4]]
xlist.remove("xyz")
print(xlist)

['abc', 123, 456, [1, 3, 4]]


In [12]:
xlist=["abc",123,456,"xyz",[1,3,4]]
xlist.pop(3)
print(xlist)

['abc', 123, 456, [1, 3, 4]]


In [15]:
xlist=["abc",123,456,"xyz",[1,3,4]]
del xlist[2]
print(xlist)

['abc', 123, 'xyz', [1, 3, 4]]


In [16]:
xlist=["abc",123,456,"xyz",[1,3,4]]
xlist.clear()
xlist.append("messi")
print(xlist)

['messi']


In [17]:
xlist=["abc",123,456,"xyz",[1,3,4]]
for i in xlist:
    print(i)

abc
123
456
xyz
[1, 3, 4]


In [19]:
xlist=["abc",123,456,"xyz",[1,3,4]]
for i in range(len(xlist)):
    print(i)

0
1
2
3
4


In [20]:
xlist=["abc",123,456,"xyz",[1,3,4]]
i=0
while i<len(xlist):
    print(xlist[i])
    i+=1

abc
123
456
xyz
[1, 3, 4]


In [21]:
xlist=["abc",123,456,"xyz",[1,3,4]]
[print(x) for x in xlist]

abc
123
456
xyz
[1, 3, 4]


[None, None, None, None, None]

In [22]:
xlist=[123,456,444,555]
xlist.sort()
print(xlist)

[123, 444, 456, 555]


In [24]:
xlist=["messi","neymar","ibrahimovic","zizou"]
xlist.sort()
print(xlist)

['ibrahimovic', 'messi', 'neymar', 'zizou']


In [25]:
xlist=["messi","neymar","ibrahimovic","zizou"]
xlist.reverse()
print(xlist)

['zizou', 'ibrahimovic', 'neymar', 'messi']


In [26]:
xlist=[999,888,765,453,23758,55455]
xlist.sort()
xlist.reverse()
print(xlist)


[55455, 23758, 999, 888, 765, 453]


In [36]:
xtup=("dre","eminem","lamar","tupac","dre")
print(len(xtup))
print(xtup[3])
xlist=list(xtup)
xlist.append("nicki minaj")
print(xlist)

5
tupac
['dre', 'eminem', 'lamar', 'tupac', 'dre', 'nicki minaj']


In [48]:
xlist=[12,22,33,44]
sum=0
for i in xlist:
    sum+=i
print(sum)

111


In [59]:
xlist=[12,22,33,44]
largest=xlist[0]
for num in xlist:
        if num > largest:
            largest = num
print(largest)

44


In [60]:
xtup = ("roman", "iyo sky", "charlotte", "batista", "hhh", "hbk", "alexa")
print(xtup[:4])

('roman', 'iyo sky', 'charlotte', 'batista')


In [61]:
xtup = ("roman", "iyo sky", "charlotte", "batista", "hhh", "hbk", "alexa")
xtup1=(1,2,3,4,5)
newtup=xtup+xtup1
print(newtup)

('roman', 'iyo sky', 'charlotte', 'batista', 'hhh', 'hbk', 'alexa', 1, 2, 3, 4, 5)


In [66]:
xtup=(1,2,3,4)
x=int(input("enter a number to check="))
if x in xtup:
    print("element present")
else:
    print("error")

enter a number to check= 3


element present


In [69]:
xtup=(1,34,12,33)
print(xtup*5)

(1, 34, 12, 33, 1, 34, 12, 33, 1, 34, 12, 33, 1, 34, 12, 33, 1, 34, 12, 33)


In [75]:
xtup=(1,1,2,2,3,1,4)
print(xtup.count(1))

3


In [86]:
xlist=[1,2,3,4,5,6,7]
even=0
odd=0
for i in xlist:
    if i%2==0:
        even+=1
    else:
        odd+=1
print("Even number count=",even)
print("odd number count=",odd)
    

Even number count= 3
odd number count= 4


In [93]:
xlist=[1,2,-9,-8,3,4,-5,5,5,6]
positive=[]
negative=[]
for i in xlist:
    if i<0:
        positive.append(i)
    else:
        negative.append(i)
print(positive)
print(negative)

[-9, -8, -5]
[1, 2, 3, 4, 5, 5, 6]


In [94]:
xlist=["iyo sky","charlotte flair","liv morgan","carmella"]
for i in range(len(xlist)):
    print(i)

0
1
2
3


In [98]:
xlist=[1,2,3,4,5,6]
num=int(input("enter a number="))
index=0
for i in range(len(xlist)):
    if xlist[i]==index:
        index=i
        break
if index!=0:
    print("item at",index)
else:
    print("item not found")

enter a number= 3


item not found


In [102]:
xset={3,7,1,4,6,5,6,7}
print(xset)
print(len(xset))
print(type(xset))

{1, 3, 4, 5, 6, 7}
6
<class 'set'>


In [103]:
xset=set((1,2,4,5,7,8,42))
print(xset)

{1, 2, 4, 5, 7, 8, 42}


In [104]:
xset={3,7,1,4,6,5,6,7}
for i in xset:
    print(i)

1
3
4
5
6
7


In [106]:
xset={3,7,1,4,6,5,6,7}
xset.add(2)
print(xset)

{1, 2, 3, 4, 5, 6, 7}


In [108]:
xset={3,7,1,4,6,5,6,7}
xlist=["messi","zizou","neymar","maldini"]
print(xlist)
xset.update(xlist)
print(xset)

['messi', 'zizou', 'neymar', 'maldini']
{1, 3, 4, 5, 6, 7, 'maldini', 'zizou', 'neymar', 'messi'}


In [114]:
xset={1,2,3,"zizou","maldini","neymar","el sherawy","svincheko"}
xset.remove("neymar")
xset.discard("svincheko")
xset.pop()
print(xset)

{2, 3, 'zizou', 'el sherawy', 'maldini'}


In [115]:
xset={"svincheko","nedved","thierry henry","figo","pique"}
for i in xset:
    print(i)

svincheko
nedved
pique
figo
thierry henry


In [129]:
xlist=[1,2,1,3,4,7,5,4,3,2,3,4,5,6,7]
xdict={}
for i in xlist:
    if i in xdict:
        xdict[i]+=1
    else:
        xdict[i]=1
print(xdict)

{1: 2, 2: 2, 3: 3, 4: 3, 7: 2, 5: 2, 6: 1}


In [29]:
xlist=[1,2,3,4,5,6,7,8,9]
xlist[7::-3]

[8, 5, 2]

In [45]:
a="hello i am nobody"
a[-11:-7]
a[::-1]
a[-2::-3]

'domilh'

In [59]:
for i in a[-11:]:
    print(i,end=' ')

i   a m   n o b o d y 

In [60]:
# 5

# 1
# 12
# 123
# 1234
# 12345

In [67]:
x=int(input("Enter limit="))
for i in range(1,x+1):
    for j in range(1,i+1):
        print(j,end='')
    print()

Enter limit= 5


1
12
123
1234
12345


In [73]:
x=input("Enter string=")
y=int(input("enter limit"))
for i in range(1,y+1):
    print(x*i)

Enter string= y
enter limit 6


y
yy
yyy
yyyy
yyyyy
yyyyyy


In [74]:
#     *
#    ***
#   *****
#  *******
# *********

In [81]:
# x=input("Enter string=")
y=int(input("enter limit"))
s=y-1
j=1
for i in range(1,y+1):
    print(s*' '+j*'*')
    s-=1
    j+=2

enter limit 4


   *
  ***
 *****
*******


In [82]:
def oddev(a):
    if(a%2==0):
        return True
    else:
        return False
        
a=int(input("Enter the number="))
oddev(a)

Enter the number= 5


odd number


In [87]:
def oddev(a):
    if(a%2==0):
        print(True)
        return True
    else:
        print(False)
        return False
        
a=int(input("Enter the number="))
b = oddev(a)
print(b)

Enter the number= 6


True
True


In [108]:
def sumnum(num1,num2):
    return num1+num2
num1=int(input("Enter num1="))
num2=int(input("Enter num2="))
sumnum(num1,num2)

Enter num1= 4
Enter num2= 5


9

In [107]:
def sumnum(num1,num2,num3=0):
    print(num1,num2)
    return num1+num2+num3
sum=sumnum(num2=6,num1=7)
print("sum of three numbers=",sum)

7 6
sum of three numbers= 13


In [4]:
def large(num1,num2,num3=10):
    if num1>num2 and num1>num3:
        return num1
    elif num2>num1 and num2>num3:
        return num2
    else:
        return num3
num1=int(input("Enter num1="))
num2=int(input("Enter num2="))
large(num1,num2)

Enter num1= 4
Enter num2= 5


10

In [14]:
def patern(limit):
    s=limit-1
    j=1
    for i in range(1,limit+1):
        print(s*' '+j*'*')
        s-=1
        j+=2
limit=int(input("Enter limit="))
patern(limit)

Enter limit= 10


         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************


In [19]:
def max1(*c):
    sum1=0
    for i in c:
        sum1+=i
    return sum1
max1(5,5,6,6,1,2,3,4,5,6,7,6,5,3,2)

66

In [21]:
def maximum(*a):
    return max(a)
maximum(1,2,3,4,5,78,98,6)

98

In [26]:
def maximum(*a):
    max1=a[0]
    for i in a:
        if i>max1:
            max1=i
    return max1
maximum(-1,-3,-5,-2,0)

0

In [30]:
def maximum(*a):
    max1=float('-inf')
    for i in a:
        if i>max1:
            max1=i
    return max1
maximum(-1,-3,-5,-2)

-1

In [38]:
def details(**a):
    print(a)
details(Name='Nithin',age=23,gender = "Male")

{'Name': 'Nithin', 'age': 23, 'gender': 'Male'}


In [50]:
def players(**x):
    print(x)

players(
    Player1='Svichenko', Position1='CF', Team='AC Milan',
    Player2='Gullit', Position2='DMF', Team2='AC Milan',
    Player3='Iniesta', Position3='CMF', Team3='FC Barcelona',
    Player4='Lionel Messi', Position4='AMF', Team4='Inter Miami',
    Player5='Cristiano Ronaldo', Position5='CF', Team5='Al Nassr',
    Player6='Neymar JR', Position6='CF', Team6='Santos FC',
    Player7='Paolo Maldini', Position7='LB', Team7='AC Milan',   
)


{'Player1': 'Svichenko', 'Position1': 'CF', 'Team': 'AC Milan', 'Player2': 'Gullit', 'Position2': 'DMF', 'Team2': 'AC Milan', 'Player3': 'Iniesta', 'Position3': 'CMF', 'Team3': 'FC Barcelona', 'Player4': 'Lionel Messi', 'Position4': 'AMF', 'Team4': 'Inter Miami', 'Player5': 'Cristiano Ronaldo', 'Position5': 'CF', 'Team5': 'Al Nassr', 'Player6': 'Neymar JR', 'Position6': 'CF', 'Team6': 'Santos FC', 'Player7': 'Paolo Maldini', 'Position7': 'LB', 'Team7': 'AC Milan'}


In [53]:
def actors(**x):
    print(x)

players(
    Actor1='Al Pacino', Film1='SCARFACE',
    Actor2='Jennifer Connelly', Film2='REQUIM OF DREAMS',
    Actor3='Brad Pitt', Film3='ONCE UPON A TIME IN HOLLYWOOD'  
)

{'Actor1': 'Al Pacino', 'Film1': 'SCARFACE', 'Actor2': 'Jennifer Connelly', 'Film2': 'REQUIM OF DREAMS', 'Actor3': 'Brad Pitt', 'Film3': 'ONCE UPON A TIME IN HOLLYWOOD'}


In [54]:
capitals = {
    "India": "New Delhi",
    "USA": "Washington D.C.",
    "Japan": "Tokyo",
    "Germany": "Berlin"
}
capitals.keys()

dict_keys(['India', 'USA', 'Japan', 'Germany'])

In [55]:
capitals.values()

dict_values(['New Delhi', 'Washington D.C.', 'Tokyo', 'Berlin'])

In [58]:
capitals.items()

dict_items([('India', 'New Delhi'), ('USA', 'Washington D.C.'), ('Japan', 'Tokyo'), ('Germany', 'Berlin')])

In [61]:
capitals['USA']

'Washington D.C.'

In [67]:
details={
    "Name":["Denzel","Valentino","Veron"],
    "Age":[56,30,27],
    "Origin":["America","Mexico","Argentina"]
}
details.items()


dict_items([('Name', ['Denzel', 'Valentino', 'Veron']), ('Age', [56, 30, 27]), ('Origin', ['America', 'Mexico', 'Argentina'])])

In [79]:
i=0
for i in range(len(details["Name"])):
    for x, vlist in details.items():
        print(f"{x}: {vlist[i]}")
    print()
    

Name: Denzel
Age: 56
Origin: America

Name: Valentino
Age: 30
Origin: Mexico

Name: Veron
Age: 27
Origin: Argentina



In [1]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "year": 2020
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}


In [5]:
x = thisdict.get("model")
print(x)

Mustang


In [10]:
y = thisdict.keys()
print(y)
thisdict["colour"]="black"
print(thisdict)


dict_keys(['brand', 'model', 'year', 'colour'])
{'brand': 'Ford', 'model': 'Mustang', 'year': 2020, 'colour': 'black'}


In [11]:
x = thisdict.items()
print(x)

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 2020), ('colour', 'black')])


In [14]:
x=thisdict.keys()
print(x)
thisdict.update({"year":1992})
print(x)

dict_keys(['brand', 'model', 'year', 'colour'])
dict_keys(['brand', 'model', 'year', 'colour'])


In [25]:
playr={
    "name":"Messi",
    "age":37,
    "team":"Inter Miami"
}
print(playr)
playr.pop("age")
print(playr)
playr.update({"position":"CF"})
playr.popitem()
del playr["name"]
print(playr)

{'name': 'Messi', 'age': 37, 'team': 'Inter Miami'}
{'name': 'Messi', 'team': 'Inter Miami'}
{'team': 'Inter Miami'}


In [26]:
arg={
    "name":"Lionel Messi",
    "position":"CF",
    "team":"Inter Miami"
}
brz={
    "name":"Neymar JR",
    "position":"AMF",
    "team":"Santos FC"
}
fra={
    "name":"Thierry Henry",
    "position":"CF",
    "team":"Arsenal"
}
plr={
    "player1":arg,
    "player2":brz,
    "player3":fra
}
print(plr)

{'player1': {'name': 'Lionel Messi', 'position': 'CF', 'team': 'Inter Miami'}, 'player2': {'name': 'Neymar JR', 'position': 'AMF', 'team': 'Santos FC'}, 'player3': {'name': 'Thierry Henry', 'position': 'CF', 'team': 'Arsenal'}}


In [1]:
import numpy as np
l=[1,2,3,4,5,6]
arr=np.array(l)
print(arr)

[1 2 3 4 5 6]


In [2]:
type(arr)

numpy.ndarray

In [3]:
doub=arr*2
print(doub)

[ 2  4  6  8 10 12]


In [4]:
arr*5

array([ 5, 10, 15, 20, 25, 30])

In [7]:
if arr.any()==7:
    print(True)
else:
    print(False)

False


In [11]:
arr

array([ 6,  7,  8,  9, 10, 11])

In [14]:
arr>9

array([False, False, False, False,  True,  True])

In [16]:
arr.ndim

1

In [19]:
arr2=np.array([[1,2],[3,4],[5,6],[7,8]])
arr2.ndim

2

In [20]:
print(arr2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
a=np.zeros((2,4),dtype=int)

In [27]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
b=np.ones((3,3,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
c=np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [35]:
d=np.arange(2,20,2)
d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
d.shape = (3,3)

In [39]:
d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
import numpy as np
arr= np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr.shape=(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [19]:
arr[0:2,0:2] =0

In [20]:
arr

array([[0, 0, 3],
       [0, 0, 6],
       [7, 8, 9]])

In [42]:
arr=np.zeros((5,5),dtype='int8')
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [43]:
arr[1:4,1:4,]=1
arr

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [44]:
type(arr[1][0])

numpy.int8

In [46]:
arr=np.array([5,6,7,8,9,10])

In [47]:
np.mean(arr)

7.5

In [48]:
np.median(arr)

7.5

In [49]:
np.std(arr)

1.707825127659933

In [52]:
print(np.min(arr))
print(np.max(arr))

5
10


In [53]:
np.prod(arr)

151200

In [59]:
np.where(arr>9,1,50)

array([50, 50, 50, 50, 50,  1])

In [61]:
unq=np.unique(arr)
unq

array([ 5,  6,  7,  8,  9, 10])

In [65]:
mark=np.array([10,12,2,5,16,26,30,45])

In [68]:
if mark.any()>25:
    print("PASSED")
else:
    print("FAILED")

FAILED


In [72]:
mark > 25

array([False, False, False, False, False,  True,  True,  True])

In [74]:
np.where(mark>25,"PASSED","FAILED")

array(['FAILED', 'FAILED', 'FAILED', 'FAILED', 'FAILED', 'PASSED',
       'PASSED', 'PASSED'], dtype='<U6')